### ISSUE TITLE
Unable to parse \"\"1\"\" 

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-sdk-c#501] opened 2023-11-28 01:30 UTC
I tried to use  device-example-c (https://github.com/edgexfoundry/device-sdk-c/blob/v3.1.0/src/c/examples/template.c)
, and add a deivce resources in TemplateProfile.json

```
{
  "name": "TemplateSensor",
  "manufacturer": "IoTechSystems",
  "model": "IoT0",
  "description": "Template Sensor",
  "labels": ["sensor"],
  "apiVersion": "v3",

  "deviceResources":
  [
    {
      "name": "SensorOne",
      "description": "A Sensor generating unsigned integer values",
      "attributes": { "SensorID": "Sen1" , "SensorType": "UInt64" },
      "properties": { "valueType": "Uint64", "readWrite": "R", "units": "things" }
    },
    {
      "name": "SensorTwo",
      "description": "A Sensor generating unsigned integer values",
      "attributes": { "SensorID": "Sen2", "SensorType": "UInt64" },
      "properties": { "valueType": "Uint64", "readWrite": "R", "units": "things" }
    },
    {
      "name": "Switch",
      "description": "A generic switch",
      "attributes": { "SensorID": "Switch1", "SensorType": "Switch" },
      "properties": { "valueType": "Bool", "readWrite": "RW", "units": "State" }
    },,
    {
      "name": "Example",
      "description": "A generic switch",
      "attributes": { "SensorID": "Example1", "SensorType": "Example" },
      "properties": { "valueType": "Uint64", "readWrite": "RW", "units": "State" }
    }
  ]
}
```

Error message :
"Unable to parse ""1"" for ...

**Comment by hechuanju** [comment] 2023-12-27 08:00
![image](https://github.com/edgexfoundry/device-sdk-c/assets/37501001/daa28f3b-4781-4222-b73b-5b2883c22f4c)

**Comment by bighb69738** [comment] 2023-12-27 08:19
@hechuanju 
I will try it again
Thank you

**Comment by FelixTing** [comment] 2024-01-16 07:25
@bighb69738 I could not reproduce the error. Are you able to successfully run the example after removing the redundant comma from your device profile?

**Comment by bighb69738** [comment] 2024-01-16 08:11
@FelixTing 
It is still fail.

**Comment by FelixTing** [comment] 2024-01-16 11:07
@bighb69738 Could you please provide detailed steps to reproduce the error?
If the error occurs during the execution of the PUT command, I believe this issue should have already been addressed by https://github.com/edgexfoundry/device-sdk-c/pull/505.

**Comment by cloudxxx8** [comment] 2024-08-02 06:19
close as no acitivity

**Closed by cloudxxx8** 2024-08-02 06:19 UTC
Labels: question
